development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: koetomo_development

test:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: koetomo_test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: koetomo_production