default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  sslmode: require

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  url: <%= ENV["DATABASE_URL_TEST"] || ENV["DATABASE_URL"] %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
